services:

  api:

    build: .

    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/f1drivers

    depends_on:
      - mongo

  mongo:

    image: mongo:latest

    ports:
      - "27017:27017"

  redis:

    image: redis:latest

    ports:
    - "6379:6379"
  
  worker1:

    build: .

    command: node src/workers/importWorker.js

    depends_on:
      - redis
      - mongo

    environment:
      WORKER_ID: worker-1
      MONGO_URI: mongodb://mongo:27017/f1drivers
  
  worker2:

    build: .

    command: node src/workers/importWorker.js

    environment:
      WORKER_ID: worker-2
      MONGO_URI: mongodb://mongo:27017/f1drivers

    depends_on:
    - redis
    - mongo

  worker3:

    build: .

    command: node src/workers/importWorker.js

    environment:
      WORKER_ID: worker-3
      MONGO_URI: mongodb://mongo:27017/f1drivers

    depends_on:
      - redis
      - mongo