services:

  api:

    build: .

    ports:
      - "5000:5000"

    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/f1drivers

    depends_on:
      - mongo

  mongo:

    image: mongo:latest

    ports:
      - "27017:27017"

  redis:

    image: redis:latest

    ports:
    - "6379:6379"