events {}

http {

    log_format custom
'$remote_addr - $remote_user [$time_local] '
'"$request" $status '
'Backend=$upstream_addr '
'Instance=$upstream_http_x_instance '
'ResponseTime=$upstream_response_time';

    access_log /var/log/nginx/access.log custom;

    upstream backend {


        server api-1:5000 weight=5 max_fails=2 fail_timeout=15s;

        server api-2:5000 weight=3 max_fails=2 fail_timeout=15s;

        server api-3:5000 weight=1 max_fails=2 fail_timeout=15s;

        
    }

    server {

        listen 80;

        location / {

            proxy_pass http://backend;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}